---
version: "3.7"
services:
  qbittorrent:
    build: ./build
    image: wcen/docker-qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    volumes:
      - "./config:/config"
      - "./data:/data"
      - "./downloads:/downloads"
      - "./watch:/watch"
    environment:
      TZ: "Asia/Taipei"
    ports:
      - "8999:8999"
      - "8999:8999/udp"
    networks:
      - internal
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    volumes:
      - "./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "50080:80"
    networks:
      - internal
networks:
  internal:
    name: internal
...