variables: variables.yml
web_server: no
schedules:
  - tasks: '*'
    interval:
      minutes: 2
tasks:
  '{? task.ttg.tag ?}':
    template: '{? task.ttg.tag ?}'
templates:
  anchors:
    _tasks: &tasks
      accept_all: yes
      no_entries_ok: yes
    _qbittorrent: &qbittorrent
      host: '{? qbittorrent.host ?}'
      port: '{? qbittorrent.port ?}'
      username: '{? qbittorrent.user ?}'
      password: '{? qbittorrent.password ?}'
  '{? task.ttg.tag ?}':
    <<: *tasks
    rss: '{? task.ttg.rss ?}'
    qbittorrent:
      <<: *qbittorrent
      label: '{? task.ttg.tag ?}'