variables: variables.yml
web_server: no
schedules:
  - tasks: '*'
    interval:
      minutes: 1
templates:
  anchors:
    _tasks: &tasks
      accept_all: yes
      no_entries_ok: yes
    _qbittorrent: &qbittorrent
      host: '{? qbt.host ?}'
      port: 8080
      username: '{? qbt.usr ?}'
      password: '{? qbt.pwd ?}'
  ttg:
    <<: *tasks
    rss: '{? rss.ttg ?}'
    qbittorrent:
      <<: *qbittorrent
      label: ttg
  mteam:
    <<: *tasks
    rss: '{? rss.mteam ?}'
    qbittorrent:
      <<: *qbittorrent
      label: mteam
tasks:
  TTG:
    template: ttg
  MTEAM:
    template: mteam